"""cairnlib.snapshot — point-in-time markdown rendering (`cairn snapshot`)
and the git-tags release-state reader.

Extracted verbatim from cairn.py (POLY-58 ruling §2 step 9).
"""

import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional, Set, Tuple

from cairnlib.constants import STATUS_ORDER
from cairnlib.errors import CairnError
from cairnlib.records import parse_frontmatter
from cairnlib.store import _dir_glob, _id_sort_key

__all__ = [
    "build_snapshot_markdown",
    "read_git_tags",
]


def build_snapshot_markdown(data_dir: Path, generated_at: Optional[str] = None) -> str:
    """Render a point-in-time markdown view of the tracker: majors, then
    milestones (roadmap), then issues grouped by status (`DEFAULT_COLUMNS`
    order + "cancelled" last) and sorted numerically by id within each
    group. Meant for `cairn snapshot >> process/STATE.md` (TRACKER.md --
    "Relationship to STATE.md").

    A RENDERING only -- never parsed back by cairn. The output deliberately
    never opens with "---" (`parse_frontmatter`'s fence) so it can't be
    mistaken for tracker data even if misplaced under issues/, milestones/,
    or majors/ -- `check_repo` reports (not silently ingests) a misplaced
    copy as a per-file parse error, same as any other malformed file.

    `generated_at` is injectable so callers (tests; a future `--as-of`) get
    determinism without wall-clock noise -- `cmd_snapshot` sources a real
    timestamp when it's None. Everything else is a pure function of
    `data_dir`'s contents, independent of filesystem scan order (majors/
    milestones sorted by id; issues grouped/sorted as above) -- two
    snapshots of an unchanged tree, given the same `generated_at`, are
    byte-identical, so appended snapshots diff cleanly.

    Per-file parse errors are skipped, not raised (mirrors `check_repo`) --
    one broken file shouldn't crash the whole rendering.
    """
    data_dir = Path(data_dir)
    if generated_at is None:
        generated_at = datetime.datetime.now().isoformat()

    majors: List[Dict[str, Any]] = []
    for p in _dir_glob(data_dir / "majors"):
        try:
            fm, _ = parse_frontmatter(p.read_text(encoding="utf-8"))
        except CairnError:
            continue
        majors.append(fm)
    majors.sort(key=lambda fm: str(fm.get("id", "")))

    milestones: List[Dict[str, Any]] = []
    for p in _dir_glob(data_dir / "milestones"):
        try:
            fm, _ = parse_frontmatter(p.read_text(encoding="utf-8"))
        except CairnError:
            continue
        milestones.append(fm)
    milestones.sort(key=lambda fm: str(fm.get("id", "")))

    issues: List[Dict[str, Any]] = []
    for p in _dir_glob(data_dir / "issues"):
        try:
            fm, _ = parse_frontmatter(p.read_text(encoding="utf-8"))
        except CairnError:
            continue
        issues.append(fm)

    lines: List[str] = []
    lines.append(f"<!-- cairn snapshot -- generated {generated_at}. Do not edit; regenerate with `cairn snapshot`. -->")
    lines.append("")
    lines.append(f"## cairn snapshot ({generated_at})")
    lines.append("")
    lines.append(
        "_Generated by `cairn snapshot` -- a point-in-time rendering, "
        "never re-parsed by cairn. Do not hand-edit; regenerate instead._"
    )
    lines.append("")

    lines.append("### Majors")
    lines.append("")
    if majors:
        for m in majors:
            lines.append(
                f"- **{m.get('id')}** — status: {m.get('status')}, "
                f"owner: {m.get('owner') or '-'}, health: {m.get('health') or '-'}"
            )
    else:
        lines.append("_None._")
    lines.append("")

    lines.append("### Roadmap")
    lines.append("")
    if milestones:
        for m in milestones:
            extras = []
            if m.get("target_tag"):
                extras.append(str(m["target_tag"]))
            if m.get("ga"):
                extras.append("GA")
            suffix = f" ({', '.join(extras)})" if extras else ""
            lines.append(
                f"- **{m.get('id')}** — {m.get('name') or '-'} "
                f"(major {m.get('major') or '-'}, {m.get('status')}){suffix}"
            )
    else:
        lines.append("_None._")
    lines.append("")

    lines.append("### Issues")
    lines.append("")
    status_order = list(STATUS_ORDER)
    if issues:
        for status in status_order:
            group = sorted(
                (i for i in issues if i.get("status") == status),
                key=lambda fm: _id_sort_key(fm.get("id")),
            )
            if not group:
                continue
            lines.append(f"#### {status}")
            lines.append("")
            for i in group:
                milestone = i.get("milestone") or "-"
                assignee = i.get("assignee") or "-"
                lines.append(
                    f"- **{i.get('id')}** — {i.get('title')} "
                    f"(milestone: {milestone}, assignee: {assignee})"
                )
            lines.append("")
        known = set(status_order)
        leftover = sorted(
            (i for i in issues if i.get("status") not in known),
            key=lambda fm: _id_sort_key(fm.get("id")),
        )
        if leftover:
            lines.append("#### (other)")
            lines.append("")
            for i in leftover:
                lines.append(f"- **{i.get('id')}** — {i.get('title')}")
            lines.append("")
    else:
        lines.append("_None._")
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def read_git_tags(data_dir: Path) -> Tuple[Optional[Set[str]], Optional[str]]:
    """PT-44 (joint ruling § 4): the release-state source of truth. Reads
    the local tag set via `git -C <data_dir> for-each-ref --format=
    %(refname:short) refs/tags` -- measured 8ms, called once per
    `build_board_payload` call (once per root, matching "once per payload
    build"). `-C data_dir` still finds the repo root by walking up from
    `data_dir` (same as any git invocation from a subdirectory) -- reads
    no file outside `process/cairn/` directly (the subprocess's own
    internal `.git` reads are not this engine touching a file, same
    reasoning `_git_mv_or_rename` already relies on for the spin-off
    constraint).

    Returns `(tag_set, None)` on success, `(None, "<warning>")` when git
    is missing or `data_dir` isn't inside a git working tree -- NEVER
    raises (the `_git_mv_or_rename` precedent: fall back, don't crash).
    Callers print the warning themselves (this function has no stderr
    side effect of its own -- matches resolve_board_columns/
    resolve_board_swimlane's "return the warning as data" convention).
    """
    import subprocess
    try:
        result = subprocess.run(
            ["git", "-C", str(data_dir), "for-each-ref", "--format=%(refname:short)", "refs/tags"],
            capture_output=True, text=True, timeout=5,
        )
    except (FileNotFoundError, OSError) as e:
        return None, f"git unavailable ({e}) -- every milestone's released will be null"
    if result.returncode != 0:
        detail = result.stderr.strip() or f"exit {result.returncode}"
        return None, f"git tag read failed ({detail}) -- every milestone's released will be null"
    tags = {line.strip() for line in result.stdout.splitlines() if line.strip()}
    return tags, None
